### ISSUE TITLE
vm2 contains CRITICAL security issues

### ISSUE THREAD

**Issue by fowlerwill** [formio/formio-workers#54]
https://github.com/formio/formio-workers/blob/3a35b8319556963bbc4bfbf46867f92f306bdecd/package.json#L35

Refs:
https://github.com/advisories/GHSA-cchq-frgv-rjh5
https://security.snyk.io/package/npm/vm2

**Comment by lane-formio** [comment]
As a result of our removal of vm2 from all of our libraries, we have deprecated formio-workers and have removed it as a dependency in the formio library >=4.00.
